//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mleczarnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productID { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string amountInPack { get; set; }
        public Nullable<int> made { get; set; }
        public Nullable<int> sold { get; set; }
    }
}
