//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mleczarnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank
    {
        public int tankID { get; set; }
        public Nullable<float> tankCapacity { get; set; }
        public Nullable<float> tankFilling { get; set; }
    }
}
